services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - ./services/api-gateway:/usr/src/app
      - api_gateway_node_modules:/usr/src/app/node_modules
    depends_on:
      - auth-service
      - patients-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/VETCARE_AUTH
      - TOKEN_SECRET=${TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - ./services/auth-service:/usr/src/app
      - auth_service_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongodb

  patients-service:
    build: ./services/patients-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/VETCARE_PATIENTS
      - TOKEN_SECRET=${TOKEN_SECRET}
    volumes:
      - ./services/patients-service:/usr/src/app
      - patients_service_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  api_gateway_node_modules:
  auth_service_node_modules:
  patients_service_node_modules:
